Feature
muhenge/Ruby_associations pull request #2
Opened 2020-06-17 12:40 UTC by muhenge

## In this project we created this task
> in this project we created 3 feature tasks using Rails active record associations 
- Setup the user sign-in feature, using sessions hash method,
- We set up a basic event creator
- We set up events attendance record

2020-06-17 15:48 UTC, Torres-ssf requested changes
### Changes Required :muscle: 
Hi there team :hand: 
Great job so far :clap: 
But before moving on there are some changes that we need to work on.

- [ ] Try to commit more often. This way you will be always committing small changes, which will make it easier to describe them. This is a best practice for many reasons and will also make your repository looks more professional. Check out [this article](https://sethrobertson.github.io/GitBestPractices/)

- [ ] As it said in the requirements, Event's index page should display past and upcoming events. In your app, you used Past and Previous events, which is misleading, both words are related to events that happen in the past.
![Screenshot from 2020-06-17 11-52-50](https://user-images.githubusercontent.com/30977845/84913608-1c506a00-b091-11ea-9332-136380c01b19.png)

- [ ] You are properly showing all events that a User is attending or has attended(On user's show page). But as it said on the requirements, that information should be separated in past and upcoming events.
![Screenshot from 2020-06-17 12-01-47](https://user-images.githubusercontent.com/30977845/84914745-5a01c280-b092-11ea-9332-b1f12f86a8bb.png)

- [ ] The Navigation links should be at the top of the page.
![Screenshot from 2020-06-17 12-03-25](https://user-images.githubusercontent.com/30977845/84914920-903f4200-b092-11ea-90a1-df31074b0427.png)

- [ ] Your app is throwing an error when I tried to log in with a non-existing user. We need to fix that
![Screenshot from 2020-06-17 12-20-19](https://user-images.githubusercontent.com/30977845/84916907-0a70c600-b095-11ea-8a9d-2f6a109c703a.png)

**[OPTIONAL]**

- [ ] You can improve your page style. You can think on ways to improve the user experience; how the information should be displayed to be easily understood by users.

Please kindly submit to code review again after making these changes.
You can message me on Slack if you have any questions.

Happy coding :computer: 
**Sergio Torres**

2020-06-18 07:20 UTC, wathigo requested changes
## Changes Required 
### Great work team :clap:
Let's fix some issues before we move on.

**REQUIRED**
* Models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from Pathwright)
* Authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from Pathwright)
* Event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from Pathwright)

See the comments for more pointers :point_down: 

**OPTIONAL**
* We can remove the attend button if the user is already and event attendee.
We can also improve on the styling of the user interface.

**After working on the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2020-06-18 07:20 UTC, wathigo commented on app/models/event.rb
> +  end
Since we already have scope for checking upcoming and past events, this will not be necessary. We can get rid of it.

2020-06-18 07:20 UTC, wathigo commented on app/models/user.rb
> +  scope :upcoming, -> { where('date >= ?', Date.today) }
We also don't need this for the user model. We don't have a date filed for a user. We only needed this for the event model.

2020-06-19 20:27 UTC, wathigo requested changes
### Changes Required.
Great work adding the tests :clap: 
I ran into some issues while attempting to run the tests.
The issues originated from missing gems and invalid configs.

**REQUIRED**
* Let's include the following gems in our Gemfile:
  ```ruby
  group :development, :test do
    gem 'rspec-rails', '~> 4.0.0'
  end
  ```
  ```ruby
  group :test do
    gem 'database_cleaner-active_record'
  end
  ```
  Including these gems will enable us to run the tests using `bundle exec rspec` successfully.
* See the comment :point_down: 

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2020-06-19 20:27 UTC, wathigo commented on config/database.yml
> +  database: ":memory"
**[REQUIRED]**
Let's use `database: db/test.sqlite3`. This will enable us to migrate the database in the test environment without any issues.

2020-06-20 06:32 UTC, mosesogwo approved these changes
**Hi @muhenge, @rindrajosia:clap:, Great work making the changes:heavy_check_mark:**
Your project is approved. But take note that your tests could be greatly improved.
- Check how you can use `shoulda_matchers` in your tests
- Make sure you understand unit tests for your models and integration tests for your features
- Group spec files in sub-folders (different folders for model specs and feature specs)

**Good luck in your next project :stars:**

### Status: Approved :heavy_check_mark:

2020-06-20 06:32 UTC, mosesogwo commented on spec/event_spec.rb
> +    expect(user1.events.first.description).to include('event_test')
For this feature test, it is more appropriate to check the page for content that signifies the event was created than to check the database record.

2020-06-29 02:36 UTC, merged